hym/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.common.views import HomeView, SignUpView, DashboardView, ProfileUpdateView, ProfileView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomeView.as_view(), name='home'),
    path('register/', SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile-update/', ProfileUpdateView.as_view(), name='profile-update'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password-change/',
        auth_views.PasswordChangeView.as_view(template_name='password-reset/password_change.html', success_url='/'),
        name='password_change'
    ),

 # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password-reset/password_reset.html',
             subject_template_name='password-reset/password_reset_subject.txt',
             email_template_name='password-reset/password_reset_email.html',
              success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),

    path('oauth/', include('social_django.urls', namespace='social')), #for social media log

    path('contact/', include('apps.common.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/common/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from apps.userprofile.models import Profile

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional")
    last_name = forms.CharField(max_length=30, required=False, help_text="Optional")
    email = forms.EmailField(max_length=255, help_text="Enter a valid email address")

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",

        ]

class UserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)

    class Meta:
        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
        ]

class ProfileForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=11, required=True)
    birth_date = forms.CharField(required=False)

    class Meta:
        model = Profile
        fields = [
            "phone_number",
            "birth_date",
            "length",
            "shoulder_back",
            "chest",
            "stomach_fit",
            "sleeve",
            "bicep_arm",
            "cuff",
            "neck",
            "head",
            "length_trouser",
            "thigh",
            "waist",
            "ankle",
            "knee",
            "calf",
            "profile_image",
        ]

templates/base.html
{% load static %}
{% load crispy_forms_tags %}

<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Hym signage</title>

  <!-- Custom fonts for this template-->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Date Time Picker CSS -->
  <link rel="stylesheet" href="{% static 'date-time-phone/jquery-ui.css' %}">
  <link rel='stylesheet' href="{% static 'date-time-phone/jquery-ui-timepicker-addon.css' %}" />
  <!-- Date Time Picker CSS -->

</head>

<style>
.fa {
  padding: 17px;
  font-size: 18px;
  width: 50px;
  text-align: center;
  text-decoration: none;
  margin: 10px 0 5px 0;
  border-radius: 50%;
}

  .fa-facebook {
  background: #3B5998;
  color: white;
}

.fa-twitter {
  background: #55ACEE;
  color: white;
}

.fa-instagram {
  background: linear-gradient(45deg, #405de6, #5851db, #833ab4, #c13584, #e1306c, #fd1d1d);
  color: white;
}
</style>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-address-card"></i>
        </div>
        <div class="sidebar-brand-text mx-3">HYM <sup>SIGNAGE</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <p class="text-center text-white font-weight-bold">Welcome {{user.first_name}}!</p>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Companies -->
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Companies</span></a>
      </li>

      <!-- Nav Item - Contact -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Contact</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Profile -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}">
          <i class="fas fa-fw fa-user"></i>
          <span>Profile</span></a>
      </li>

      <!-- Nav Item - Change Password -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'password_change' %}">
          <i class="fas fa-fw fa-key"></i>
          <span>Change Password</span></a>
      </li>

      <!-- Nav Item - Logout -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">
          <i class="fas fa-fw fa-sign-out-alt"></i>
          <span>Logout</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        {% include 'common/messages.html' %}

        {% block content %}

        {% endblock content %}


      </div>
      <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <footer class="py-3 bg-grey">
    <p class="m-0 text-dark text-center ">
    </p>
     <p class="m-0 text-dark text-center ">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="https://twitter.com/yovire_" class="fa fa-twitter"></a>
                    <a href="http://instagram.com/Yovire" class="fa fa-instagram"></a>
                </p>
    <p class="m-0 text-dark text-center ">Copyright &copy; HYM CRM 2030. All Rights Reserved.</p>
</footer>

  {% block script %}  {% endblock script %}

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>

  <!-- Date Time Picker JS -->
  <script src="{% static 'date-time-phone/jquery-ui.js' %}" ></script>
  <script src="{% static 'date-time-phone/jquery-ui-timepicker-addon.js' %}"></script>

  <script>
    $( function() {
        // $( "#id_birth_date" ).datetimepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
        // $( "#id_birth_date" ).timepicker({ dateFormat: 'yy-mm-dd', maxDate: 0, controlType: 'select'}).attr("autocomplete", "off") ;
        $( "#id_birth_date" ).datepicker({ dateFormat: 'yy-mm-dd' }).attr("autocomplete", "off") ;
    });
  </script>
  <!-- Date Time Picker JS -->

  <!-- Phone Mask JS -->
  <script src="{% static 'date-time-phone/jquery-input-mask-phone-number.min.js' %}"></script>

  <script>
    //(xxx) xxx-xxxx format code
    $(document).ready(function () {
        $('#id_phone_number').usPhoneFormat({
            format: '(xxx) xxx-xxxx',
        });
    });
  </script>
  <!-- Phone Mask JS -->

</body>

</html>